# Generated by Django 2.2 on 2019-06-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
    ]
